[package]
name = "zeeland"
description = "A painless HTTP bridge generator"
version = "0.1.0"
edition = "2021"
license = "APACHE-2.0 OR MIT"
repository = "https://github.com/dnbln/zeeland"

[dependencies]
