
[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5", features = ["json"]}
serde = {version = "1", features = ["derive"]}
hello_world = { path = ".." }

[workspace]
