[package]
name = "cargo-zeeland"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pathdiff = "0.2"